version: "3.8"

volumes:
  php-fpm-socket:
  db-store:

services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./api:/var/www/api
    depends_on:
      - api
      - front

  api:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./api:/var/www/api
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=chat
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    ports:
      - "8080:8080"

  front:
    build:
      context: .
      dockerfile: ./infra/docker/nuxt/Dockerfile
    command: yarn run dev
    volumes:
      - ./front:/var/www/front
    ports:
      - "3000:3000"

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=chat
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
